version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: japlearn-db
    restart: always
    environment:
      POSTGRES_USER: japlearn_user
      POSTGRES_PASSWORD: japlearn_password
      POSTGRES_DB: japlearn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: japlearn-adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
